version: '3.3'

services:
  garmin:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
  garmin-dev:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/dev/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/dev/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      XDEBUG_MODE: "coverage"
      PHP_IDE_CONFIG: serverName=garmin-dev # This needs to be in under PHP -> Servers -> Name (Set to garmin)
    tty: true